### ISSUE TITLE
Feature Request : 978 support for other feeders

### ISSUE THREAD

**Issue by dlasher** [tsunghanliu/adsb-box.snap#47]
Several other services (radarbox for example) have started adding support for 978mhz feeds, like Flightaware has. I've been running dual USB-SDR for a long time, works perfectly with Flightware. (And thank you for adding support)

Poking around, I don't see any way to mirror the 978 feed out to other feeds like we're doing with the 1080mhz feeds.

If I'm not seeing it, please share how? If it's not already possible, consider this a feature request.

Thank you!

**Comment by tsunghanliu** [comment]
Hi @dlasher ,

Previously I have added necessary configs for rbfeeder accroding this [post](https://forum.radarbox24.com/index.php?PHPSESSID=net5hev4sdic2l1p5qis0kbeda&topic=103271.msg444091#msg444091) on Radarbox Forum.
But I'm not able to verify if this really work.

Could you please provide the content of `/var/snap/adsb-box/current/rbfeeder/rbfeeder.ini` of your feeder?
Also the output of `sudo snap logs -n all adsb-box.rbfeeder` might help.
P.S. you probably need to restart rbfeeder first by running `sudo snap restart adsb-box.rbfeeder`, wait 5+ minutes and run the `sudo snap logs ...` command, otherwise it will only provide statistics data.

**Comment by dlasher** [comment]
As requested:

`
[client]
network_mode=true
log_file=/var/log/rbfeeder.log
lat=XX
lon=YY
alt=ZZ
key=--my-key---
sn=EXTRxxxxxx
sat_used=0
sat_visible=0
[network]
mode=beast
external_port=30005
external_host=127.0.0.1

[mlat]
autostart_mlat=true
`

**Comment by dlasher** [comment]
added

[dump978]
dump978_enabled=true
dump978_port=30979

as suggested - verified that 30979 was listening (dump978-fa) - and restarted all the services.

My station does show up : https://www.radarbox.com/stations/uat978

Guess I'll have to wait a bit, see if it shows up on their site.

**Comment by tsunghanliu** [comment]
That's great news!
Then I will update the script used to update `rbfeeder.ini`. I supposed the keyword `[dump978]` should be already there, but it's not in this case.

**Comment by dlasher** [comment]
> That's great news! Then I will update the script used to update `rbfeeder.ini`. I supposed the keyword `[dump978]` should be already there, but it's not in this case.

Thank you again for not only the great snap you built and maintain, but the quick response. \tip.hat\

**Comment by dlasher** [comment]
978 support is working just fine - closing this request.
