### ISSUE TITLE
FR24 not updating on i386

### ISSUE THREAD

**Issue by ChapmanShaw** [tsunghanliu/adsb-box.snap#64]
When "sudo snap refresh adsb-box" is entered, FR24 remains as old version on i386 machine.

**Comment by tsunghanliu** [comment]
Hi,

Is your system a x64 system? If yes, it would be better to use the amd64 version instead of i386. Because i386 is no longer support officially by Ubuntu and some dependencies of feeders are not available after Ubuntu 20.04. So I don't tend to update feeders of the i386 version.

Anyhow, I checked the i386 version of fr24feed and it's using static link, i.e., likely it doesn't have the dependency issue. I could probably update it for i386 platform, but I cannot guarantee it will work.

**Comment by tsunghanliu** [comment]
the test version (v1.5.3-1-g2425527) is released to the `edge` channel.

use the following instruction to try the version:
```
$ sudo snap refresh adsb-box --edge

# to revert to the original version/channel
$ sudo snap refresh adsb-box --stable
```

**Comment by ChapmanShaw** [comment]
**Thank you. That worked.** 
It was only noticeable because Flightradar24 had started expecting a newer version. My system was connecting to the server, but it was not accepting my feed. I was not getting credited.

I use an old Asus Eee PC with a Intel Atom 32-bit processor, in my garage. Debian installs fine.

**Comment by tsunghanliu** [comment]
Thanks for testing. I'm going to bump the version and release `v1.5.4` to all channels.

Regarding i386 support, I understand that there are still many good enough i386 devices for ADS-B feeder. I would consider how to extend the support period.

Cheers,

**Comment by tsunghanliu** [comment]
v1.5.4 (rev 834) has been released to all channels.

You might want to switch back to the stable channel.
